# Generated by Django 4.0.4 on 2023-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_person_participant_firstname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participant',
            name='clubNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
